version = 0.1
[default.deploy.parameters]
stack_name = "uade-valorar-app"
resolve_s3 = true
s3_prefix = "uade-valorar-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["ScikitLearnInferenceFunction=221082204664.dkr.ecr.us-east-1.amazonaws.com/samapp7427b055/scikitlearninferencefunctionc862108arepo"]
disable_rollback = true
confirm_changeset = true
